"""initial

Revision ID: 11eb55ccedb8
Revises: 
Create Date: 2024-08-22 21:22:48.624492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11eb55ccedb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('create schema bet_maker')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', postgresql.ENUM('WAITING', 'W1', 'W2', name='eventstatusenum', schema='bet_maker', inherit_schema=True), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('odds', sa.Numeric(precision=100, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event')),
    schema='bet_maker'
    )
    op.create_index(op.f('ix_bet_maker_event_id'), 'event', ['id'], unique=False, schema='bet_maker')
    op.create_table('bet',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('WAITING', 'WON', 'LOST', name='betstatusenum', schema='bet_maker', inherit_schema=True), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('odds', sa.Numeric(precision=100, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['bet_maker.event.id'], name=op.f('fk_bet_event_id_event'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bet')),
    schema='bet_maker'
    )
    op.create_index(op.f('ix_bet_maker_bet_id'), 'bet', ['id'], unique=False, schema='bet_maker')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('drop schema bet_maker')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bet_maker_bet_id'), table_name='bet', schema='bet_maker')
    op.drop_table('bet', schema='bet_maker')
    op.drop_index(op.f('ix_bet_maker_event_id'), table_name='event', schema='bet_maker')
    op.drop_table('event', schema='bet_maker')
    # ### end Alembic commands ###
